const Map<String, String> ar = {
  'welcome': 'مـرحبــا بـك',
  'uniEmail': 'البريد الإلكتروني',
  'pleaseEnterYourUniversityEmail': 'الرجاء إدخال البريد الإلكتروني',
  'password': 'كلمة السر',
  'pleaseEnterYourPassword': 'الرجاء إدخال كلمة السر',
  'logIn': 'دخول',
  'clear': 'مسح',
  "CannotFindAccount": "الحساب غير موجود",
  "findAnAccountWith": "لا يوجد حساب يستخدم البريد الإلكتروني",
  "pleaseEnterCorrectEmail": "الرجاء إدخال بريد إلكتروني صحيح",
  'incorrectPassword': 'كلمة السر خاطئة',
  'thePasswordouEnteredIsIncorrect':
      'كلمة السر التي تم إدخالها خاطئة، من فضلك حاول مجددا',
  'logOut': 'تسجيل الخروج',
  'areYouSureYouWantToLogOut': 'هل أنت متأكد من عملية تسجيل الخروج؟',
  'Cancel': 'إلغاء',
  'ok': 'موافق',
  'confirm': 'تأكيد',
  'availablelib': 'متاحة',
  'closed': 'مغلقة',
  'libraryisClosed': 'المكتبة مغلقة',
  'youCannotBookNow': 'لا يمكنك الحجز الآن',
  'currentBookingDetails': 'تفاصيل الحجز الحالي',
  'bookSearch': 'البحث عن كتاب',
  'bookASeat': 'حجز مقعد',
  'bookingDetails': 'تفاصيل الحجز',
  'upcomingNews': 'الأحداث القادمة',
  'showMore': 'مشاهدة المزيد',
  'librarySections': 'أقسام المكتبة',
  'readMore': 'إقرأ المزيد',
  'studyRooms': 'قاعات المطالعة',
  'available': 'متاح',
  'pending': 'قيد الانتظار',
  'unAvailable': 'غير متاح',
  'studentName': 'اسم الطالب',
  'studentID': 'رقم الطالب',
  'studyRoomName': 'اسم القاعة',
  'tabelNum': 'رقم الطاولة',
  'seatNum': 'رقم المقعد',
  'bookingTime': 'وقت الحجز',
  'bookValidation': 'صلاحية الحجز',
  'cancelBooking': 'إنهاء الحجز',
  'bookingConfirmed': 'تم تأكيد الحجز',
  'bookingSuccessfullyConfirmed': 'تمت عملية تأكيد الحجز بنجاح',
  'homePage': 'الصفحة الرئيسية',
  'confirmBooking': 'تأكيد الحجز',
  'bookYourSeat': 'إحجز مقعدك',
  'showBookingInfo': 'عرض تفاصيل الحجز',
  'table': 'طاولة',
  'searchForABook': 'ابحث عن كتاب..',
  'askTheBot': 'إسأل Bot',
  'writeYourMessage': 'اكتب رسالتك',
  'services': 'الخدمات',
  'whoAreWe': 'من نحن',
};
