const Map<String, String> en = {
  'welcome': 'Welcome',
  'uniEmail': 'University Email',
  'pleaseEnterYourUniversityEmail': 'Please Enter Your University Email',
  'password': 'Password',
  'pleaseEnterYourPassword': 'Please Enter yYour Password',
  'logIn': 'Log In',
  'clear': 'Clear',
  "CannotFindAccount": "Can't Find Account",
  "findAnAccountWith": "We can't find an account with",
  "pleaseEnterCorrectEmail": "Please Enter correct Email",
  'incorrectPassword': 'Incorrect Password',
  'thePasswordouEnteredIsIncorrect':
      'The password you entered is incorrect. Please try again',
  'logOut': 'Log Out',
  'areYouSureYouWantToLogOut': 'Are You Sure You Want To Log Out?',
  'Cancel': 'cancel',
  'ok': 'OK',
  'confirm': 'Confirm',
  'availablelib': 'Available',
  'closed': 'Closed',
  'libraryisClosed': 'Library is Closed',
  'youCannotBookNow': 'You Cannot Book Now',
  'currentBookingDetails': 'Current Booking Details',
  'bookSearch': 'Book Search',
  'bookASeat': 'Book a Seat',
  'bookingDetails': 'Booking Details',
  'upcomingNews': 'Upcoming News',
  'showMore': 'Show More',
  'librarySections': 'Library Sections',
  'readMore': 'Read More',
  'studyRooms': 'Study Rooms',
  'available': 'Available',
  'pending': 'Pending',
  'unAvailable': 'UnAvailable',
  'studentName': 'Student Name',
  'studentID': 'Student Id',
  'studyRoomName': 'Study Room Name',
  'tabelNum': 'Tabel Number',
  'seatNum': 'SeatNumber',
  'bookingTime': 'Booking Time',
  'bookValidation': 'Book Validation',
  'cancelBooking': 'Cancel Booking',
  'bookingConfirmed': 'Booking Confirmed',
  'bookingSuccessfullyConfirmed': 'The booking has been successfully confirmed',
  'homePage': 'Home Page',
  'confirmBooking': 'Confirm Booking',
  'bookYourSeat': 'Book Your Seat',
  'showBookingInfo': 'Show Booking Info',
  'table': 'Table',
  'searchForABook': 'Search for a Book..',
  'askTheBot': 'Ask the Bot',
  'writeYourMessage': 'Write Your Message',
  'services': 'Services',
  'whoAreWe': 'Who Are We',
};
